name             'chef-lxc-container'
maintainer       'PE, pf.'
maintainer_email 'peychart@mail.pf'
license          'GNU Public License 3.0'
description      'Installs/Configures chef-lxc-container'
long_description 'Installs/Configures chef-lxc-container'
version          '0.1.0'
